### ISSUE TITLE
Sequence count label too short

### ISSUE THREAD

**Issue by chrissearle** [dbaldwin/DronePan#28]
Getting 3/.. instead of 3/40 or whatever

**Comment by dbaldwin** [comment]
Why do you think that is? I have place holder text of Photo: 45/45 just to make sure we could support double digits both on the count and the total.

**Comment by chrissearle** [comment]
Just to answer the question above:

Because the update code updated it to Sequence: nn/mm - and Sequence is longer than Photo.

The fix was to change it to match - so that it sets Photo nn/mm.
