### ISSUE TITLE
DJIBatteryDelegate not called

### ISSUE THREAD

**Issue by chrissearle** [dbaldwin/DronePan#50]
Seems that after updating to 3.1.1 - the battery delegate (DJIBatteryDelegate) isn't seeing calls to battery didUpdateState - at least for Osmo.

**Comment by chrissearle** [comment]
We set the delegate here

https://github.com/dbaldwin/DronePan/blob/master/DronePan/BatteryController.swift#L39

And the delegate method is

https://github.com/dbaldwin/DronePan/blob/master/DronePan/BatteryController.swift#L42-L48

I can step thru - it sets the delegate but never goes into didUpdateState.

Works in 3.1

**Comment by dbaldwin** [comment]
Have you tested this on any aircraft yet?

**Comment by dbaldwin** [comment]
Confirmed this is broken with the P4.

**Comment by dbaldwin** [comment]
From DJI:

Answer: We tried both Phantom 4 and Osmo. The battery push info is normal. The following screenshot is the push info for the Osmo. Could you please provide us a piece of the code to let us figure out where the problem is.

**Comment by chrissearle** [comment]
Fixed in d8c1ab5d27cf86c20ae545e222ef6c7defa57e60
