### ISSUE TITLE
Incorrect model

### ISSUE THREAD

**Issue by chrissearle** [dbaldwin/DronePan#52]
On moving to background and returning - you sometimes get the wrong model returned from the SDK.

Seen in 3.1.1 at least with Osmo - being identified as a Phantom 3 Professional.

**Comment by dbaldwin** [comment]
I get Phantom 4 100% of the time during my testing. Will move on to others.

**Comment by chrissearle** [comment]
OK - I have seen this several times on 3.1.1 - but not yet on 3.2 (but I haven't had a lot of testing time on 3.2 yet).

**Comment by dbaldwin** [comment]
From DJI:

Answer: This seems to be a bug to us. We would record it and try to reproduce it.

**Comment by chrissearle** [comment]
So far - still only repeated in 3.1.1 - could be very intermittent in 3.2 though

**Comment by chrissearle** [comment]
Going to close this. Re-open if we see it in 3.2 or later
