### ISSUE TITLE
For narrow lenses one nadir doesn't seem to be enough

### ISSUE THREAD

**Issue by chrissearle** [dbaldwin/DronePan#67]
See https://www.facebook.com/groups/dronepan/permalink/267587736927148/

**Comment by dbaldwin** [comment]
Maybe we give options of 1, 2 (180 degrees), and 4 (90 degrees)? In the original version of DronePan I had it taking the same # of photos at nadir as the other rows. Users complained it was too much. So bumping up to 2 or 4 seems like a good next step.

**Comment by chrissearle** [comment]
Yes - I was thinking a 1-4 scale here. Settings window. Looking at the image supplied - he'd need a 4. But more than 4 seems like overkill.
