### ISSUE TITLE
Sky row naming

### ISSUE THREAD

**Issue by chrissearle** [dbaldwin/DronePan#72]
Is the name "Sky Row" misleading? What we're saying is "allow it to go above (osmo -> below) the horizon. But - it's not a single row - if we allow above the horizon and also more than 3 rows (so 4 with the sky row) - we evenly space the rows - so more than one is above the horizon.

Actually - I'd like to change the behaviour so that it doesn't increase the row count - it's just a flag to say "start at horizontal" or "start at gimbal pitch limit".

**Comment by chrissearle** [comment]
Thinking this should be a toggle:
- Upper limit is horizon (0˚)
- Upper limit is [gimbal limit in degrees]

(switch upper limit to lower limit for handheld).

Only issue is we'd need to feed the limit from the gimbal object into settings to show it.

Then number of rows is just "how many rows spaced evenly from the chosen limit.

**Comment by dbaldwin** [comment]
I think that makes sense. Perhaps as additional clarification we can dynamically display the row spacing in degrees. For example:
- Upper limit = 30
- Number of rows = 6
- Row spacing = 20 degrees

**Comment by chrissearle** [comment]
Related to #74
