### ISSUE TITLE
Info view not appearing on pano start - 1.4.3b8

### ISSUE THREAD

**Issue by chrissearle** [dbaldwin/DronePan#73]
Needs to be checked - code looks right but the info view did not appear on pano start (iPhone 6+)

**Comment by dbaldwin** [comment]
So I understand this bug are you stating that the telemetry at the bottom doesn't display on mobile? I know it's fine on tablet (iPad Mini 2).

**Comment by chrissearle** [comment]
I didn’t see any telemetry info on my iPhone for all 4 panos (info view at bottom)

I don't know if that's due to the fact that it's a phone or some other reason - but I haven't had time to debug it yet.
