### ISSUE TITLE
Start and stop icons 3x

### ISSUE THREAD

**Issue by chrissearle** [dbaldwin/DronePan#84]
We need 3x icons to go along with the 2x and 1x versions.

It would also help in the UI builder if there was no padding (on all sizes) - so that the edges of the frame almost clip the circle.

**Comment by dbaldwin** [comment]
Look for play_button and stop_button in here: https://www.dropbox.com/sh/qrtv29p5tv4m8fa/AAApnA6ElutqRF9hcUtZAz43a?dl=0
