### ISSUE TITLE
Fix API keys for papertrail

### ISSUE THREAD

**Issue by chrissearle** [dbaldwin/DronePan#92]
Update online logging (app delegate) to use dronepan papertrail rather than mine (should be just replacing two keys).

I'm not worried that the keys are public via github - it does allow people to send fake logs - but if that turns out to be a real issue we can deal with it then.

Assigning to @dbaldwin since I think he's the one with the correct keys :)

**Comment by dbaldwin** [comment]
Had taken care of this previously here:

https://github.com/dbaldwin/DronePan/commit/7f2640b455d62ae24d968566f686ba73ec9b663f

**Comment by chrissearle** [comment]
Good to have it confirmed. Thanks.
